### ISSUE TITLE
ERROR:  integer out of range

### ISSUE THREAD

**Issue by sercoin** [woodbri/osrm-tools#1]
Hi,

I create my tables same as "ddnoded2" tables. But when I try to run pgr2osrm I got this error;

Writing vertices to streets.osrm file ... ERROR:  integer out of range

How can I solve that? Can you help me?

**Comment by woodbri** [comment]
Hmmm, looking at the code, I seem to have a small bug. I will push a change for this. Line 135 of pgr2osrm.cpp

```
int32_t lat = row["lat"].as<uint32_t>();
```

should be:

```
int32_t lat = row["lat"].as<int32_t>();
```

**Comment by woodbri** [comment]
Closing. 37057c6..550a555 fix pushed to master.

**Comment by sercoin** [comment]
Creating names table ...
  Writing streets.osrm.names file ... 1775 records
  Writing vertices to streets.osrm file ... ERROR:  integer out of range

I still get this error. I changed line 135 like you said.

**Comment by woodbri** [comment]
What does `select min(id), max(id) from vertices_tmp;` report?
`id` values must be unsigned 32bit integers.

**Comment by sercoin** [comment]
Results are min(id)=1  max(id)=65329

**Comment by woodbri** [comment]
Are your coordinates in lat/lon degrees? What does this report:
`select min(st_x(the_geom)), min(st_y(the_geom)), max(st_x(the_geom)), max(st_y(the_geom)) from vertices_tmp;`

**Comment by sercoin** [comment]
5194199.72306648   ;3315880.66657522;   5390616.28540176;    3516524.91557929 in this order

**Comment by woodbri** [comment]
You data is not in decimal degrees. This is required by OSRM.
You will need to project all you data into srid 4326.
